language: node_js #語言

node_js: stable #語言版本

before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- npm install -g npm@latest

install:
  - npm install #安裝 hexo 及 插件

script: #要執行的程式
  - hexo cl # 清除
  - hexo g # 生成

after_success: #執行完成後的 git push
  - cd ./public
  - git init
  - git config user.name "bnmghjtyu0" #github名稱
  - git config user.email "bnmghjtyu0@gmail.com" #email
  - git add .
  - git commit -m "Travis Ci 更新"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches: #分支
  only:
    - develop #只監聽hexo分支
env:
 global:
   - GH_REF: github.com/bnmghjtyu0/bnmghjtyu0.github.io.git  #设置GH_REF，記得更改yourname